// <auto-generated />
namespace Term_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initModelContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initModelContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202411170346576_initModelContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
